version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: 192.168.99.100
#      KAFKA_CREATE_TOPICS: cff_train_position:1:1
      AUTO_CREATE_TOPIC_ENABLE: true
      LOG_RETENTION_HOURS_PER_TOPIC: 0.1
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  cff-mock-feeder:
    build: .
    depends_on:
      - kafka
