version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_CREATE_TOPICS: "cfftrainposition:1:1,cffstationboard:1:1"
      LOG_RETENTION_HOURS_PER_TOPIC: 0.1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  streaming_backend:
    build: components/play-realtime/
    #image: octoch/cff-poc-streaming-backend:0.1.2
    #ports:
    #  - "81:9000"
    links:
      - kafka
  cff_feeder:
    #build: components/node_cff_sniff
    #built with cd components/node_cff_sniff && docker build --tag=alexmass/alexmass/cff-node-sniff .
    #deployed with docker push alexmass/alexmass/cff-node-sniff:xx
	image: alexmass/cff-node-sniff
    environment:
      KAFKA_HOST: kafka
    dns: 8.8.8.8
    links:
      - kafka
  web_realtime_viewer:
    #build: components/web-realtime-viewer
    #built with cd components/web-realtime-viewer && docker build --tag=alexmass/cff-web-realtime-viewer .
    #deployed with docker push alexmass/cff-web-realtime-viewer:xx
    image: alexmass/cff-web-realtime-viewer
    links:
      - streaming_backend
    ports:
      - "82:80"
  nginx:
    build: components/nginx
    ports:
      - "80:80"
    links:
      - streaming_backend
      - web_realtime_viewer
