version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.0.1
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_CREATE_TOPICS: "cfftrainposition:1:1,cffstationboard:1:1"
      LOG_RETENTION_HOURS_PER_TOPIC: 0.1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  streaming_backend:
    image: alexmass/cff-play-realtime:0.2.5
    #build: alexmass/cff-play-realtime:0.1
    #cd components/play-realtime ; ./activator docker:publish ; cd - 
    #ports:
    #  - "81:9000"
    links:
      - kafka
  cff_feeder:
    #build: components/node-sniff
    #built & deployed with 
    #cd components/node-sniff ; docker build --tag=alexmass/cff-node-sniff:0.1.2 . ; cd - ; docker push alexmass/cff-node-sniff:0.1.2
    #d
    image: alexmass/cff-node-sniff:0.1.2
    environment:
      KAFKA_HOST: kafka
    dns: 8.8.8.8
    links:
      - kafka
  web_realtime_viewer:
    #build: components/web-realtime-viewer
    #built  & deployed with 
    #cd components/web-realtime-viewer ; docker build --tag=alexmass/cff-web-realtime-viewer:0.1.4 . ; cd -; docker push alexmass/cff-web-realtime-viewer:0.1.4
    image: alexmass/cff-web-realtime-viewer:0.1.4
    links:
      - streaming_backend
    ports:
      - "82:80"
  nginx:
    image: alexmass/cff-nginx:0.2.2
    #cd components/nginx ; docker build --tag=alexmass/cff-nginx:0.2.2 . ; cd -; docker push alexmass/cff-nginx:0.2.2
    ports:
      - "80:80"
    links:
      - streaming_backend
      - web_realtime_viewer
